# Generated by Django 4.0.2 on 2022-05-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='cathegory',
            field=models.CharField(choices=[('M', '+Mayor de Edad'), ('ME', '-Menor de Edad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
