# Generated by Django 4.0.2 on 2022-05-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_actors_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors_id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='actors_id',
        ),
    ]
