# Generated by Django 4.0.2 on 2022-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_movies_actors_id_remove_series_actors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='companies',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
