# Generated by Django 4.0.2 on 2022-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_movies_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='companies',
        ),
        migrations.AddField(
            model_name='movies',
            name='companies_name',
            field=models.ManyToManyField(to='articulos.Companies'),
        ),
    ]
