# Generated by Django 4.0.2 on 2022-05-12 23:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_remove_movies_companies_name_delete_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='companies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item One'), (2, 'Item Two')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
