# Generated by Django 4.0.2 on 2022-05-12 23:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_movies_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='companies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item One'), (2, 'Item T')], max_length=3),
        ),
    ]
