# Generated by Django 4.0.2 on 2022-05-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_remove_movies_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='director_id',
            new_name='director_f',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='director_id',
            new_name='director_f',
        ),
        migrations.AddField(
            model_name='movies',
            name='genero_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.genero'),
        ),
    ]
