# Generated by Django 4.0.2 on 2022-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_rename_director_f_movies_directorf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imgProcess/'),
        ),
    ]
