# Generated by Django 4.0.2 on 2022-05-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0021_alter_movies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='generof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.genero'),
        ),
        migrations.AddField(
            model_name='series',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imgProcess/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cathegory',
            field=models.CharField(choices=[('M', '+Mayor de Edad'), ('ME', '-Menor de Edad')], max_length=2),
        ),
    ]
